[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
wallet_program = "JAhYJ65vcpkpTXqjZ2kNyvwr19h4j2xvVeExrk5tdbci"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/wallet_program.ts"
