[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
usdc_sender = "F7gCMvxedC5XnCJR6pT9JL8rQ13s6K2NzcwW3CWbnkrs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
