[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
wallet_program = "AqTPKZr4jsWKHPtUWBd2gScwQi2Narducnc77SggATdR"

[programs.mainnet]
wallet_program = "RB57sATNhML6QK289L8gmLekytJxgzwxFS8UN2WsnWB"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "https://palpable-small-research.solana-mainnet.quiknode.pro/6560ff623d16431ae52c578a1544033913f29174/"
cluster = "devnet"
# wallet = "/root/.config/solana/hades.json"
wallet = "/root/.config/solana/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
