[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
usdc_sender = "7pB3zj3voieg4msvT7oTxc6xRDDPDjiCy3J4Sr4ogPaC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
