[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
wallet_program = "HbHtUUTSrfqJ5BGBC7ydnTRqirh61nYdVe9KYvgPh1G9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
